package com.towerswatson.rto.dpo.services._2010._01;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "DpoService", targetNamespace = "http://towerswatson.com/rto/dpo/services/2010/01")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DpoService {

	/**
	 * 
	 * @param parameters
	 * @return returns com.towerswatson.rto.dpo.services._2010._01.PofResponse
	 * @throws DpoServiceGetPofConfigurationFaultContractFaultFaultMessage
	 * @throws DpoServiceGetPofSevereFaultContractFaultFaultMessage
	 */
	@WebMethod(operationName = "GetPof", action = "http://towerswatson.com/rto/dpo/services/2010/01/DpoServiceContract/GetPof")
	@WebResult(name = "PofResponse", targetNamespace = "http://towerswatson.com/rto/dpo/services/2010/01", partName = "parameters")
	public PofResponse getPof(
			@WebParam(name = "PofRequest", targetNamespace = "http://towerswatson.com/rto/dpo/services/2010/01", partName = "parameters") PofRequest parameters)
			throws DpoServiceGetPofConfigurationFaultContractFaultFaultMessage,
			DpoServiceGetPofSevereFaultContractFaultFaultMessage;

	/**
	 * 
	 * @param parameters
	 * @return returns com.towerswatson.rto.dpo.services._2010._01.PofResponse2
	 * @throws DpoServiceGetPofWithIdConfigurationFaultContractFaultFaultMessage
	 * @throws DpoServiceGetPofWithIdSevereFaultContractFaultFaultMessage
	 */
	@WebMethod(operationName = "GetPofWithId", action = "http://towerswatson.com/rto/dpo/services/2010/01/DpoServiceContract/GetPofWithId")
	@WebResult(name = "PofResponse2", targetNamespace = "http://towerswatson.com/rto/dpo/services/2010/01", partName = "parameters")
	public PofResponse2 getPofWithId(
			@WebParam(name = "PofRequestUsingMasterSet", targetNamespace = "http://towerswatson.com/rto/dpo/services/2010/01", partName = "parameters") PofRequestUsingMasterSet parameters)
			throws DpoServiceGetPofWithIdConfigurationFaultContractFaultFaultMessage,
			DpoServiceGetPofWithIdSevereFaultContractFaultFaultMessage;

	/**
	 * 
	 * @param parameters
	 * @return returns com.towerswatson.rto.dpo.services._2010._01.PofResponse2
	 * @throws DpoServiceGetPofWithKeyConfigurationFaultContractFaultFaultMessage
	 * @throws DpoServiceGetPofWithKeySevereFaultContractFaultFaultMessage
	 */
	@WebMethod(operationName = "GetPofWithKey", action = "http://towerswatson.com/rto/dpo/services/2010/01/DpoServiceContract/GetPofWithKey")
	@WebResult(name = "PofResponse2", targetNamespace = "http://towerswatson.com/rto/dpo/services/2010/01", partName = "parameters")
	public PofResponse2 getPofWithKey(
			@WebParam(name = "PofRequestUsingKey", targetNamespace = "http://towerswatson.com/rto/dpo/services/2010/01", partName = "parameters") PofRequestUsingKey parameters)
			throws DpoServiceGetPofWithKeyConfigurationFaultContractFaultFaultMessage,
			DpoServiceGetPofWithKeySevereFaultContractFaultFaultMessage;

}
